version: '2'
services:
  php:
    image: php:8.1
    volumes:
      - ./:/app
    ports:
      - '8081:8081'
    working_dir: '/app'
    command: ./init.sh
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'yii2basic'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    expose:
      - '3306'
